server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DATASOURCE_URL}
    username: ${USER_DATASOURCE_USERNAME}
    password: ${USER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: YourHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${NamingServerURL}