version: '3.8'
services:
  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8000"
    depends_on:
      app:
        condition: service_started

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  app:
    build: ./main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://maindb:3306/musicdiary
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      discovery-service:
        condition: service_started
      maindb:
        condition: service_healthy

  maindb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: musicdiary
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  userdb:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: users
    volumes:
      - userdb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db:
  userdb: