version: '3.8'

services:
   gateway-service:
     image: eclipse-temurin:17-jdk
     volumes:
       - ./gateway-service:/app
       - gateway-gradle-cache:/home/gradle/.gradle  # Gradle 캐시 유지
     working_dir: /app
     command: ["sh", "-c", "chmod +x ./gradlew && ./gradlew bootRun --no-daemon"] # Gradle로 실행
     env_file:
       - ./env/gateway-service.env
     ports:
       - "8000:8000"
     depends_on:
       discovery-service:
         condition: service_started  
       app:
         condition: service_started 
   discovery-service:
     image: eclipse-temurin:17-jdk
     volumes:
       - ./discovery-service:/app
       - discovery-gradle-cache:/home/gradle/.gradle 
     working_dir: /app
     command: ["sh", "-c", "chmod +x ./gradlew && ./gradlew bootRun --no-daemon"]
     env_file:
       - ./env/discovery-service.env
     ports:
       - "8761:8761"
   app:
     image: eclipse-temurin:17-jdk
     volumes:
       - ./main-service:/app
       - app-gradle-cache:/home/gradle/.gradle  
     working_dir: /app
     command: ./gradlew bootRun --no-daemon  
     env_file:
       - ./env/app.env
     ports:
      - "8080:8080"
     depends_on:
       maindb:
        condition: service_started
   user-service:
     image: eclipse-temurin:17-jdk
     volumes:
       - ./user-service:/app
       - user-gradle-cache:/home/gradle/.gradle  
     working_dir: /app
     command: ./gradlew bootRun --no-daemon  
     env_file:
       - ./env/user-service.env
     ports:
      - "8001:8080"
     depends_on:
       userdb:
        condition: service_started

   maindb:
    image: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: musicdiary
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

   userdb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: users
    volumes:
      - userdb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db:
  userdb:
  gateway-gradle-cache: 
  discovery-gradle-cache:  
  user-gradle-cache:  
  app-gradle-cache: 
