server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-Filters:
        - name: CustomFilter
          args:
            baseMessage: this is base Massege
            preLogger: True
            postLogger: True
      routes:
        - id: main-service
          uri: lb://MAIN-SERVICE/
          predicates:
            - Path=/main-service/login
            - Method=POST
          filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/main-service/(?<segment>.*), /$\{segment}
        - id: main-service
          uri: lb://MAIN-SERVICE/
          predicates:
            - Path=/main-service/review/all
            - Method=GET
          filters:
            - JwtFilter
            - RewritePath=/main-service/(?<segment>.*), /$\{segment}
token:
  secret: mynameiskyeongminyeomcascascasavasvasvsvascascasajsnvnvsjkvnqvnqwiovnsaovknvakssa
  issuer: user-service

              #        - id: user-service
#          uri: lb://USER-SERVICE/
#          predicates:
#            - Path=/user-service/login
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        - id: user-service
#          uri: lb://USER-SERVICE/
#          predicates:
#            - Path=/user-service/register
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        - id: user-service
#          uri: lb://USER-SERVICE/
#          predicates:
#            - Path=/user-service/**
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

