server:
  port: 8080
spring:
  application:
    name: review-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: YourHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${NAMING_SERVER_URL}
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_SERVER_URL}/api/v2/spans"

resilience4j:
  circuitbreaker:
    instances:
      circuitbreaker:
        sliding-window-size: 10
        failure-rate-threshold: 40 # 100개의 요청 중 40개 실패시 서킷 브레이커 open(실행)
        wait-duration-in-open-state: 10000 #서킷 브레이커 오픈 시 유지하는 시간
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true